[package]
name = "jamebot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11", default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model", "framework", "standard_framework"] }
tokio = { version = "1.21.2", features = ["macros", "signal", "rt-multi-thread"] }
tracing = "0.1.37"
execute = "0.2.11"