[package]
name = "jamebot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.5.5"
tokio = { version = "1.28.2", features = ["macros", "signal", "rt-multi-thread"] }
sqlx = { version = "0.6.3", features = ["macros", "runtime-tokio-rustls", "postgres", "offline"] }
rand = "0.8.5"
reqwest = "0.11.18"
serde = "1.0.164"

openssl = { version = "0.10", features = ["vendored"] } # for cross compiling
